name: 'Setup MacPorts'
description: >-
  Configure and install MacPorts on a Mac OS runner.
branding:
  icon: box
  color: blue
inputs:
  parameters:
    description: |
      Pathname to a configuration file for the GHA-INSTALL-MACPORTS
      action. When no pathname is provided, the configuration is
      expected to be found under
      
        .github/parameters/gha-install-macports.yaml

      It is however no error when this file is not present.
      
      The configuration file is in YAML and has the following format:

        version: '2.9.3'
          The MacPorts version to install.
        prefix: '/opt/local'
          The installation prefix to install MacPortd to.
          Currently the only supported value is '/opt/local'.
        variants.select: []
          The list of selected variants in the global variants
          configuration.

          See Also variants.conf(5).

        variants.deselect: []
          The list of deselected variants in the global variants
          configuration.

          See Also: variants.conf(5).
          
        sources: ['rsync://rsync.macports.org/macports/release/tarballs/ports.tar']
          The list of source locations for port definitions. The first
          entry of the list is marked with default.

          See Also: sources.conf(5)

        ports: []
           The list of additional ports to install. Each term of the
           list is a dictionart with the mandatory 'name' holding the name
           of the port to install, optional key 'select' for the list of
           selected variants for this port, and the optional 'key'
           deselect for the list of deselected variants for this port.
    required: true
    default: ':no-value'
outputs:
  package:
    value: ${{ steps.configure-macports.outputs.package }}
    description: >-
      The URL of the package used for the MacPorts installation.
  prefix:
    value: ${{ steps.configure-macports.outputs.prefix }}
    description: >-
      The installation prefix for the MacPorts installation.
  version:
    value: ${{ steps.configure-macports.outputs.version }}
    description: >-
      The MacPorts version installed.
runs:
  using: 'composite'
  steps:
    - name: 'Identify self'
      shell: sh
      run: |
        ${{ github.action_path }}/identify_self "${{ github.action_path }}"
    - name: 'Validate Inputs'
      shell: sh
      run: |
        ${{ github.action_path }}/validate_configuration "${{ inputs.parameters }}"
    - name: 'Configure MacPorts'
      id: configure-macports
      shell: sh
      env:
        TOPLEVELDIR: ${{ github.action_path }}
      run: |
        ${{ github.action_path }}/configure_macports "${{ inputs.parameters }}"
    - name: 'Install MacPorts'
      shell: sh
      run: |
        ${{ github.action_path }}/install_macports
      env:
        TOPLEVELDIR: ${{ github.action_path }}
        macports_prefix: ${{ steps.configure-macports.outputs.prefix }}
        macports_version: ${{ steps.configure-macports.outputs.version }}
